### ISSUE TITLE
Add API for creating a Testcontainer with auto-termination 

### ISSUE THREAD

**Issue by oleg-nenashev** [wiremock/wiremock-testcontainers-go#27]
### Proposal

It would be nice to encapsulate the following code to simplify the tests.

```golang
	// Create Container
	ctx := context.Background()
	container, err := RunContainer(ctx,
		WithMappingFile("hello", "hello-world.json"),
	)
	if err != nil {
		t.Fatal(err)
	}

	// Clean up the container after the test is complete
	t.Cleanup(func() {
		if err := container.Terminate(ctx); err != nil {
			t.Fatalf("failed to terminate container: %s", err)
		}
	})
```

## Scope

- [ ] Add a new API method to the library
- [ ] Update unit tests to use the new method
- [ ] Update the documentation, especially QuickStart and examples

### References

- https://golang.testcontainers.org/features/garbage_collector/

**Comment by Vayras** [comment]
Hi @oleg-nenashev I'm currently learning Go and would like to work on this issue can you assign me this issue and tell me about the project structure?

**Comment by oleg-nenashev** [comment]
@Vayras sure, please feel free to go ahead! The project structure is really simple: just one file and the test file for it in the repository root. The rest are the documentation and the examples that can be updated as we go

**Comment by Vayras** [comment]
@oleg-nenashev Thank you for letting me know , working on this issue now

**Comment by Vayras** [comment]
I have created a pull request for this issue
